name: cc-project

services:
  client-gateway:
    build:
      context: ./client-gateway
    container_name: client-gateway
    ports:
      - "3000:3000"
    networks:
      - network

  order_manager_db:
    image: mysql:8.0
    container_name: order-manager-database
    restart: always # change this to on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${ORDER_MANAGER_DB_PASSWORD}
      - MYSQL_DATABASE=${ORDER_MANAGER_DB_DATABASE}
    volumes:
      - order_manager_data:/var/lib/mysql  # Persist database data
    ports:
      - "3306:3306"  # Expose MySQL for external connections


  order-manager:
    build:
      context: ./order-manager
    container_name: order-manager
    depends_on:
      - order_manager_db
    environment:
      - DB_USER=${ORDER_MANAGER_DB_USER}  # Use the service name as the hostname
      - DB_PORT=${ORDER_MANAGER_DB_PORT}
      - DB_PASSWORD=${ORDER_MANAGER_DB_PASSWORD}
      - DB_DATABASE=${ORDER_MANAGER_DB_DATABASE}
      - DB_HOST=${ORDER_MANAGER_DB_HOST}
    ports:
      - "3000:3000"
    networks:
      - network

networks:
  network:
   driver: bridge


volumes:
  order_manager_data:
