# This file was made to create the images quicker and to test in a docker environment (not K8s)
# However, the built image still works for k8s: USAGE: docker-compose build
name: cc-project

services:
  client-gateway:
    build:
      context: ./client-gateway
    container_name: client-gateway
    ports:
      - "3000:3000"
    networks:
      - network

  mysql:
    image: mysql:8.0
    container_name: cc-project-mysql
    restart: always # change this to on-failure
    volumes:
      - mysql-volume:/var/lib/mysql  # Persist database data
    ports:
      - "3306:3306"  # Expose MySQL for external connections

  order-manager:
    build:
      context: ./order-manager
    container_name: order-manager
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - network

  matching-engine:
    build:
      context: ./matching-engine
    container_name: matching-engine
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - network

  market-data-publisher:
    build:
      context: ./market-data-publisher
    container_name: market-data-publisher
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - network

  exchange-dashboard:
    build:
      context: ./exchange-dashboard
    container_name: exchange-dashboard
    depends_on:
      - market-data-publisher
    ports:
      - "3000:80"
    networks:
      - network

networks:
  network:
   driver: bridge


volumes:
  mysql-volume:
