apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: b3JkZXJfbWFuYWdlcl9kYg==
---
# Volume for order manager db
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
---
# Volume claim for order manager db
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
# init script
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    USE order_manager_db;

    CREATE TABLE IF NOT EXISTS orders (
      secnum INT AUTO_INCREMENT PRIMARY KEY,
      timestamp DATETIME NOT NULL,
      price DECIMAL(65, 2) NOT NULL,
      symbol VARCHAR(255) NOT NULL,
      quantity INT NOT NULL,
      quantity_left INT NOT NULL,
      side VARCHAR(255) NOT NULL,
      CHECK (quantity_left >= 0)
      );
---
# Deployment manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      initContainers:
      - name: init-mysql-script
        image: busybox
        command: ['sh', '-c', 'cp /config/init.sql /docker-entrypoint-initdb.d/']
        volumeMounts:
        - name: init-script
          mountPath: /config
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mysql-deployment
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
          volumeMounts:
              - mountPath: /var/lib/mysql
                name: mysql-storage
              - mountPath: /docker-entrypoint-initdb.d
                name: mysql-initdb
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
      volumes:
          - name: mysql-storage
            persistentVolumeClaim:
              claimName: mysql-pvc
          - name: init-script
            configMap:
              name: mysql-init-script
          - name: mysql-initdb
            emptyDir: {}
---
# Service manifest of the database
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-deployment
  type: ClusterIP



