apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-project-matching-engine
  labels:
    app: matching-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
        - name: matching-engine
          image: cc-project-matching-engine:latest
          ports:
            -  containerPort: 3000
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_HOST
              value: "mysql"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
          imagePullPolicy: Never  # Use this for local images
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: matching-engine
spec:
  selector:
    app: matching-engine
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
