# Client gateway manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-project-client-gateway-deployment
  labels:
    app: client-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-gateway
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: client-gateway
          image: cc-project-client-gateway:latest
          ports:
            -  containerPort: 3000
          imagePullPolicy: Never  # Use this for local images
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
# Load balancer for client gateway
apiVersion: v1
kind: Service
metadata:
  name: cc-project-client-gateway-load-balancer
spec:
  selector:
    app: client-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
# Order manager secrets
apiVersion: v1
kind: Secret
metadata:
  name: order-manager-secret
type: opaque
data:
  password: cm9vdA==
  database: b3JkZXJfbWFuYWdlcl9kYg==
---
# Order manager manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-project-order-manager-deployment
  labels:
    app: order-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager
          image: cc-project-order-manager:latest
          ports:
            -  containerPort: 3000
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: order-manager-secret
                  key: database
            - name: DB_HOST
              value: "order-manager-db"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-manager-secret
                  key: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
          imagePullPolicy: Never  # Use this for local images
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
# Order manager service
apiVersion: v1
kind: Service
metadata:
  name: cc-project-order-manager
spec:
  selector:
    app: order-manager
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: ClusterIP

