# Order manager manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-project-order-manager-deployment
  labels:
    app: order-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-manager
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager
          image: cc-project-order-manager:latest
          ports:
            -  containerPort: 3000
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_HOST
              value: "mysql"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
          imagePullPolicy: Never  # Use this for local images
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
# Order manager service
apiVersion: v1
kind: Service
metadata:
  name: order-manager
spec:
  selector:
    app: order-manager
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

